### ISSUE TITLE
Saving settings for channel-messenger - config.saveAll is not a function

### ISSUE THREAD

**Issue by bissolli** [botpress/modules#24]
I can't save my settings through the Dashboard, getting the following error on my logs:

```
TypeError: config.saveAll is not a function
    at /my-chatbot/node_modules/@botpress/channel-messenger/bin/webpack:/src/index.js:212:16
    at Layer.handle [as handle_request] (/my-chatbot/node_modules/express/lib/router/layer.js:95:5)
    at next (/my-chatbot/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/my-chatbot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/my-chatbot/node_modules/express/lib/router/layer.js:95:5)
    at /my-chatbot/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/my-chatbot/node_modules/express/lib/router/index.js:335:12)
    at next (/my-chatbot/node_modules/express/lib/router/index.js:275:10)
    at /my-chatbot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/my-chatbot/node_modules/raw-body/index.js:224:16)
    at done (/my-chatbot/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/my-chatbot/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
```

**Comment by bissolli** [comment]
Closing issue.
Moved to the central repository.
https://github.com/botpress/v12/issues/279
